# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b89b14c616ddabe47e16b7e505f110f883a760369a5656e48cbd1e870be35a493dc3e0067dedb98b86c5fb211a75afa3ffe697703ee0794d2daae0840c3493

test:
  secret_key_base: 45676480a1b2e0e760340b51a170682d5d1268833bd0a4db89a169d42fac9a2cf85dc600946c7595fa7c7e8629854627c5fffe8e5549546dd29a805ef0141879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
